backend/api/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.v1.urls')),
    path('', include('services.products_module.urls')),
    path('authentication/', include('services.user_module.urls.auth_urls')),
    path('profile/', include('services.user_module.urls.profile_urls')),
    path('reservation/', include('services.user_module.urls.reservation_urls')),

    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/services/file_module/models.py
import os

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

import settings
from uuid import uuid4


def get_file_path(instance, filename):
    branch_expansion = filename.split('.')
    ext = branch_expansion[-1]
    return f'{instance.content_type.model}/{instance.object_id}/{uuid4()}.{ext}'


class File(models.Model):
    file = models.FileField(upload_to=get_file_path, verbose_name='File')
    object_id = models.PositiveIntegerField(null=True, db_index=True, verbose_name='Object id')
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
        null=True,
        db_index=True,
        verbose_name='Content type'
    )
    object = GenericForeignKey(for_concrete_model=False)

    class Meta:
        verbose_name = 'File'
        verbose_name_plural = 'Files'

    def delete(self, *args, **kwargs):
        try:
            os.remove(self.file.url[1:])
        except FileNotFoundError:
            pass

        super(File, self).delete(*args, **kwargs)

    @property
    def absolute_file_url(self):
        return f'{settings.SITE_URL}{self.file.url}'

    def __str__(self):
        return str(self.file)

backend/services/products_module/models.py
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.db import models

from services.file_module.models import File

User = get_user_model()


class Category(models.Model):
    title = models.CharField(max_length=256)

    def __str__(self):
        return self.title


class Currency(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title')
    symbol = models.CharField(max_length=1, verbose_name='Symbol')
    price = models.FloatField(verbose_name='Price')
    is_default = models.BooleanField(default=False, verbose_name='Default')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.is_default:
            if not Currency.objects.filter(is_default=True).exists():
                self.is_default = True
        else:
            Currency.objects.filter(is_default=True).update(is_default=False)
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        if self.is_default:
            currency = Currency.objects.first()
            if currency:
                currency.is_default=True
                currency.save()


class Product(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title')
    description = models.TextField(max_length=2000, verbose_name='Description')
    price = models.FloatField(verbose_name='Price')
    category = models.ManyToManyField(Category,
                                verbose_name='Category',
                                related_name='products')
    currency = models.ForeignKey(Currency,
                                 on_delete=models.CASCADE,
                                 verbose_name='Currency',
                                 related_name='products')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Owner', related_name='products')
    in_stock = models.BooleanField(default=True, verbose_name='In Stock')

    @property
    def owner_email(self):
        return self.owner.email

    @property
    def files(self):
        files = File.objects.filter(object_id=self.id,
                                    content_type_id=ContentType.objects.get_for_model(Product).id)
        if files.exists():
            return files[0].absolute_file_url

backend/services/user_module/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    is_seller = models.BooleanField(default=False, verbose_name='Seller')


    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    # TODO додати створення налаштувань у методі save

    def save(self, *args, **kwargs):
        from services.products_module.models import Currency
        if not Currency.objects.exists():
            currency = Currency.objects.create(title='USD', symbol='$', price=0)
        else:
            currency = Currency.objects.first()
        super().save(*args, **kwargs)
        UserSettings.objects.get_or_create(user=self, currency=currency)


class UserAddress(models.Model):
    country = models.CharField(max_length=255, verbose_name='Country', null=True, blank=True)
    city = models.CharField(max_length=255, verbose_name='City', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Address', null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='User', related_name='user_address')


class UserSettings(models.Model):
    currency = models.ForeignKey('products_module.Currency',
                                 on_delete=models.CASCADE,
                                 verbose_name='Currency',
                                 related_name='user_settings')
    is_send_push = models.BooleanField(default=True, verbose_name='Send Push')
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='User', related_name='user_settings')


# class UserReservation(models.Model):
#     first_name = models.CharField(max_length=200)
#     last_name = models.CharField(max_length=200)
#     email = models.EmailField()
#     one = '1'
#     two = '2'
#     three = '3'
#     four = '4'
#     five = '5'
#     people_choices = ((one, 'one person'), (two, 'two people'), (three, 'three people'),
#                       (four, 'four people'), (five, 'five  people'))
#     people = models.CharField(max_length=1, choices=people_choices, default=one)
#     date = models.DateField()
#     time = models.TimeField()
#     # pending = "pending"
#     # confirmed = "confirmed"
#     # status_choices = ((pending, "pending"), (confirmed, "confirmed"))
#     # status = models.CharField(
#     #     max_length=10, choices=status_choices, default=pending)
#     comment = models.TextField(blank=True)
#
#     def __str__(self):
#         return self.first_name

backend/services/products_module/forms.py
from django import forms

from services.products_module.models import Product, Currency


class UpdateProductForm(forms.ModelForm):
    in_stock = forms.BooleanField(widget=forms.CheckboxInput(), required=False)
    file = forms.FileField(required=False)
    currency = forms.ModelChoiceField(
        queryset=Currency.objects.all(),
        to_field_name='pk',
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Product
        # fields = ('title', 'description', 'price', 'currency_id', 'in_stock')
        fields = ('title', 'description', 'price', 'category', 'in_stock', 'currency')

backend/admin/templates/auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Auth</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body class="text-center">
<main class="form-signin w-100 m-auto">
  <form>
    <img class="mb-4" src="https://www.clker.com/cliparts/z/T/r/4/K/w/sign-in-hi.png" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="text" class="form-control" id="floatingName" placeholder="First name" fdprocessedid="e71cvob">
      <label for="floatingName">First name</label>
    </div>
    <div class="form-floating">
      <input type="text" class="form-control" id="floatingSurname" placeholder="Last name" fdprocessedid="e71cvob">
      <label for="floatingSurname">Last name</label>
    </div>
    <div class="form-floating">
      <input type="text" class="form-control" id="floatingUsername" placeholder="Username" fdprocessedid="e71cvob">
      <label for="floatingUsername">Username</label>
    </div>
    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" placeholder="example@gmail.com" fdprocessedid="e71cvob">
      <label for="floatingInput">Email</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password" fdprocessedid="x05yth">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="form-check text-start my-3">
      <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault">
      <label class="form-check-label" for="flexCheckDefault">
        Remember me
      </label>
    </div>
    <a href="http://localhost:8080/" class="btn btn-primary w-100 py-2">Sign in</a>
    <p class="mt-5 mb-3 text-body-secondary">© 2020–2023</p>
  </form>
</main>
</body>

</html>

backend/admin/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
<header class="p-3 text-bg-dark" style="background: black">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
          <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <button type="button" class="btn btn-outline-light me-2"><a href="http://localhost:8080/reservation/" style="text-decoration: none; color: white">Book a table</a></button>
          <button type="button" class="btn btn-warning"><a href="http://localhost:8080/authentication/registration/" style="text-decoration: none; color: white">Sign up</a></button>
        </div>
      </div>
    </div>
  </header>

    {% block content %}
    {% endblock %}

  <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>© 2020–2023 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
  </footer>
</body>
</html>

backend/admin/templates/categories.html
{% extends "base.html" %}
{% load static %}

{% block content %}

{% for product in products %}
  <div class="card" style="width: 18rem;">
    {% if product.files %}
        <img src="{{ product.files }}" style="width: 100%; height: 100%" alt="">
    {% endif %}
    <div class="col-md-7 {% if product.id|divisibleby:'2' %} order-md-2 {% endif %}">
      <h5 class="card-title">{{ product.title }}</h5>
      <p>{{ product.description }}</p>
      <p>category :
        {% for category in product.category.all %}{{ category }}{% endfor %}
      </p>
      <p>{{ product.price }} {{ product.currency.symbol }}</p>
    </div>
  </div>
{% endfor %}


{% endblock %}

backend/admin/templates/create_update_product.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <main>
    <div class="py-5 text-center">
      <img class="d-block mx-auto mb-4" src="/docs/5.3/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
      <h2>{{ subject }}</h2>
    </div>

    <div class="row justify-content-md-center">
      <div class="col-md-6  col-sm-11">
        <form method="POST" enctype="multipart/form-data" class="needs-validation" novalidate="">{% csrf_token %}
          <div class="row g-3">

            <label for="id_file" class="form-label">File</label>
            <input type="file" name="file" id="id_file">

            <div class="col-12">
              <label for="id_title" class="form-label">Title</label>
              <input class="form-control" name="title" value="{{ form.data.title }}" id="id_title" placeholder="you@example.com">
              <div class="invalid-feedback">
                Please enter a valid title
              </div>
            </div>

            <div class="col-12">
              <label for="id_description" class="form-label">Description</label>
              <textarea class="form-control" value="{{ form.data.description }}" placeholder="Leave a comment here" id="id_description" name="description" style="height: 100px"></textarea>
              <div class="invalid-feedback">
                Please enter a valid description
              </div>
            </div>

            <div class="col-12">
              <label for="id_price" class="form-label">Price</label>
              <input type="text" class="form-control" value="{{ form.data.price }}" id="id_price" name="price">
              <div class="invalid-feedback">
                Please enter your price
              </div>
            </div>

            <div class="col-12">
                <select class="form-select" id="id_currency" name="currency" aria-label="Floating label select example">
                  {% for currency in currency_list %}
                    <option {% if form.data.currency == currency or not form.data.currency and currency.is_default %} selected {% endif %} value=" {{currency.pk }}">{{ currency.title }}</option>
                  {% endfor %}
                </select>
              <label for="id_currency" class="form-label">Currency</label>
              <div class="invalid-feedback">
                Please enter a valid Currency
              </div>
              <div class="col-12">
                <input class="form-check-input" type="checkbox" value="" id="id_in_stock" name="in_stock">
                <label class="form-check-label" for="id_in_stock">
                  Stock
                </label>
              </div>
            </div>

          <hr class="my-4">

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="send_push">
            <label class="form-check-label" for="send_push">Send Push</label>
          </div>
          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="seller">
            <label class="form-check-label" for="seller">Seller</label>
          </div>

          <button class="w-100 btn btn-primary btn-lg" type="submit">Registration</button>
        </form>
      </div>
    </div>
  </main>
</div>
{% endblock %}

backend/admin/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <section id="hero" class="d-flex align-items-center">
    <div class="container position-relative text-center text-lg-start aos-init aos-animate" data-aos="zoom-in" data-aos-delay="100">
      <div class="row">
        <div class="col-lg-8">
          <h1>Welcome to <span>Restaurantly</span></h1>
          <h2>Delivering great food for more than 18 years!</h2>

          <div class="btns">
            <a href="#menu" class="btn-menu animated fadeInUp scrollto">Our Menu</a>
            <a href="http://localhost:8080/reservation/" class="btn-book animated fadeInUp scrollto">Book a Table</a>
          </div>
        </div>
        <div class="col-lg-4 d-flex align-items-center justify-content-center position-relative aos-init aos-animate" data-aos="zoom-in" data-aos-delay="200">
          <a href="https://www.youtube.com/watch?v=u6BOC7CDUTQ" class="glightbox play-btn"></a>
        </div>

      </div>
    </div>
  </section>



  <section id="menu" class="menu section-bg">
    <div class="container aos-init aos-animate" data-aos="fade-up">

      <div class="section-title">
        <h2>Menu</h2>
        <p>Check Our Tasty Menu</p>
      </div>

      <nav aria-label="..." style="display: flex; justify-content: center">
        <ul class="pagination pagination-sm">
          <li class="page-item active" aria-current="page">
            <span class="page-link">All</span>
          </li>
          {% for category in categories %}
            <li class="page-item"><a class="page-link" href="{% url 'category' category.id %}">{{ category.title }}</a></li>
          {% endfor %}
        </ul>
      </nav>

      <div class="row menu-container aos-init aos-animate" data-aos="fade-up" data-aos-delay="200" style="position: relative;">

          {% for product in products %}
              <div class="card" style="width: 18rem;">
                {% if product.files %}
                    <img src="{{ product.files }}" style="width: 100%; height: 100%" alt="">
                {% endif %}
<!--                <img src="https://bootstrapmade.com/demo/templates/Restaurantly/assets/img/menu/lobster-bisque.jpg" alt="">-->
                <div class="col-md-7 {% if product.id|divisibleby:'2' %} order-md-2 {% endif %}">
                  <h5 class="card-title">{{ product.title }}</h5>
                  <p>{{ product.description }}</p>
                  <p>category :
                    {% for category in product.category.all %}{{ category }}{% endfor %}
                  </p>
                  <p>{{ product.price }} {{ product.currency.symbol }}</p>
                </div>
              </div>
          {% endfor %}
      </div>

      <ul class="pagination">
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">«</span>
          </a>
        </li>
        {% for i in pages_count|get_range %}
          <li class="page-item {% if i == page_number %} active {% endif %}"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endfor %}
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">»</span>
          </a>
        </li>
      </ul>



      <section id="gallery" class="gallery">

      <div class="container aos-init aos-animate" data-aos="fade-up">
        <div class="section-title">
          <h2>Gallery</h2>
          <p>Some photos from Our Restaurant</p>
        </div>
      </div>

      <div class="container-fluid aos-init aos-animate" data-aos="fade-up" data-aos-delay="100">
        <div class="row g-0">

          <div class="col-lg-3 col-md-4">
            <div class="gallery-item">
              <a href="" class="gallery-lightbox" data-gall="gallery-item">
                <img src="https://bootstrapmade.com/demo/templates/Restaurantly/assets/img/gallery/gallery-1.jpg" alt="" class="img-fluid">
              </a>
            </div>
          </div>

          <div class="col-lg-3 col-md-4">
            <div class="gallery-item">
              <a href="" class="gallery-lightbox" data-gall="gallery-item">
                <img src="https://bootstrapmade.com/demo/templates/Restaurantly/assets/img/gallery/gallery-2.jpg" alt="" class="img-fluid">
              </a>
            </div>
          </div>

          <div class="col-lg-3 col-md-4">
            <div class="gallery-item">
              <a href="" class="gallery-lightbox" data-gall="gallery-item">
                <img src="https://bootstrapmade.com/demo/templates/Restaurantly/assets/img/gallery/gallery-3.jpg" alt="" class="img-fluid">
              </a>
            </div>
          </div>

          <div class="col-lg-3 col-md-4">
            <div class="gallery-item">
              <a href="" class="gallery-lightbox" data-gall="gallery-item">
                <img src="https://bootstrapmade.com/demo/templates/Restaurantly/assets/img/gallery/gallery-4.jpg" alt="" class="img-fluid">
              </a>
            </div>
          </div>

          <div class="col-lg-3 col-md-4">
            <div class="gallery-item">
              <a href="" class="gallery-lightbox" data-gall="gallery-item">
                <img src="https://bootstrapmade.com/demo/templates/Restaurantly/assets/img/gallery/gallery-5.jpg" alt="" class="img-fluid">
              </a>
            </div>
          </div>

          <div class="col-lg-3 col-md-4">
            <div class="gallery-item">
              <a href="" class="gallery-lightbox" data-gall="gallery-item">
                <img src="https://bootstrapmade.com/demo/templates/Restaurantly/assets/img/gallery/gallery-6.jpg" alt="" class="img-fluid">
              </a>
            </div>
          </div>

          <div class="col-lg-3 col-md-4">
            <div class="gallery-item">
              <a href="" class="gallery-lightbox" data-gall="gallery-item">
                <img src="https://bootstrapmade.com/demo/templates/Restaurantly/assets/img/gallery/gallery-7.jpg" alt="" class="img-fluid">
              </a>
            </div>
          </div>

          <div class="col-lg-3 col-md-4">
            <div class="gallery-item">
              <a href="" class="gallery-lightbox" data-gall="gallery-item">
                <img src="https://bootstrapmade.com/demo/templates/Restaurantly/assets/img/gallery/gallery-8.jpg" alt="" class="img-fluid">
              </a>
            </div>
          </div>

        </div>

      </div>
    </section>
    </div>
  </section>
{% endblock %}

backend/admin/templates/my_products.html
{% extends "base.html" %}

{% block content %}

  <div class="container marketing">
    <a class="btn btn-outline-success justify-content-end" href="{% url 'create_product' %}" role="button">Create</a>
    <hr class="featurette-divider">
    {% for product in products %}
      <div class="card" style="width: 18rem;">
        {% if product.files %}
            <img src="{{ product.files }}" style="width: 100%; height: 100%" alt="">
        {% endif %}
<!--                <img src="https://bootstrapmade.com/demo/templates/Restaurantly/assets/img/menu/lobster-bisque.jpg" alt="">-->
        <div class="col-md-7 {% if product.id|divisibleby:'2' %} order-md-2 {% endif %}">
          <h5 class="card-title">{{ product.title }}</h5>
          <p>{{ product.description }}</p>
          <p>category :
            {% for category in product.category.all %}{{ category }}{% endfor %}
          </p>
          <p>{{ product.price }} {{ product.currency.symbol }}</p>
        </div>
      </div>
    {% endfor %}
</div>
{% endblock %}

backend/admin/templates/product.html
{% extends "base.html" %}

{% block content %}
  <div class="container marketing">
      {% for product in products %}
          <div class="card" style="width: 18rem;">
            {% if product.files %}
                <img src="{{ product.files }}" style="width: 100%; height: 100%" alt="">
            {% endif %}
    <!--                <img src="https://bootstrapmade.com/demo/templates/Restaurantly/assets/img/menu/lobster-bisque.jpg" alt="">-->
            <div class="col-md-7 {% if product.id|divisibleby:'2' %} order-md-2 {% endif %}">
                <h5 class="card-title">{{ product.title }}</h5>
                <p>{{ product.description }}</p>
                <p>category :
                    {% for category in product.category.all %}{{ category }}{% endfor %}
                </p>
                <p>{{ product.price }} {{ product.currency.symbol }}</p>
            </div>
          </div>
      {% endfor %}

      <div class="row">
          <div class=""><a class="btn btn-outline_primary" href="{% url 'product_update' product.id %}" role="button">Update</a></div>
          <div class=""><a class="btn btn-outline-danger" href="{% url 'product_delete' product.id %}" role="button">Delete</a></div>
      </div>

      <ul class="pagination">
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">«</span>
          </a>
        </li>
        {% for i in pages_count|get_range %}
          <li class="page-item {% if i == page_number %} active {% endif %}"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endfor %}
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">»</span>
          </a>
        </li>
      </ul>
</div>
{% endblock %}

backend/admin/templates/profile.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <main>
    <div class="py-5 text-center">
      <img class="d-block mx-auto mb-4" src="/docs/5.3/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
      <h2>Registration</h2>
    </div>

    <div class="row justify-content-md-center">
      <div class="col-md-6  col-sm-11">
        <form method="POST" class="needs-validation" novalidate="">{% csrf_token %}
          <div class="row g-3">

            <div class="col-sm-6">
              <label for="id_first_name" class="form-label">First name</label>
              <input type="text" class="form-control" name="first_name" id="id_first_name" placeholder="" value="" required="">
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-sm-6">
              <label for="id_last_name" class="form-label">Last name</label>
              <input type="text" class="form-control" name="last_name" id="id_last_name" placeholder="" value="" required="">
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>

            <div class="col-12">
              <label for="id_email" class="form-label">Email</label>
              <input type="email" class="form-control" name="email" id="id_email" placeholder="you@example.com">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="col-12">
              <label for="id_password" class="form-label">Password</label>
              <input type="password" class="form-control" name="password" id="id_password">
              <div class="invalid-feedback">
                Please enter a valid password for shipping updates.
              </div>
            </div>

            <div class="col-md-2">
              <label for="currency" class="form-label">Currency</label>
              <select class="form-select" id="currency" required="">
                <option value="">Choose...</option>
                <option>$</option>
              </select>
              <div class="invalid-feedback">
                Please select a valid currency.
              </div>
            </div>
          </div>

          <hr class="my-4">

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="send_push">
            <label class="form-check-label" for="send_push">Send Push</label>
          </div>
          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="seller">
            <label class="form-check-label" for="seller">Seller</label>
          </div>

          <button class="w-100 btn btn-primary btn-lg" type="submit"><a href="http://localhost:8080/" style="text-decoration: none; color: white">Registration</a></button>
        </form>
      </div>
    </div>
  </main>
</div>
{% endblock %}